spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_java?createDatabaseIfNotExist=true
    username: myuser
    password: 123123
  jpa:
    show-sql: true


